development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jumbotron_development
  pool: 5
  username: root
  password: root
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jumbotron_production
  pool: 5
  username: root
  password: root
